/* Shared screen + flow data for the R2 galleries and flow map.
   Source of truth: edit here; index-r2.html, flowmap-r2.html and
   the artifact builder all consume this file. */
const SECTIONS = [
  ['Sign in & sign up', [
  ['welcome','Sign in','One step: phone number, code by text.',
   'Subline now leads with the at-home service. "Create an account" is finally visible.', false],
  ['signup','Create account','Four fields. That is the whole form.',
   'Net new. The old sign-up funneled documents, dependents and insurance before any care; identity is enough to start.', true],
  ['verify','Text code','One code serves sign-in and sign-up.',
   'Net new. Each digit box is its own 46&times;56 target, above the 44px floor.', true],
  ]],
  ['Main navigation', [
  ['home','Home','The hero is now the thing only Teleport does.',
   '<b>Crew first:</b> "A licensed nurse, at your door" leads; the video visit is one quiet row below it.', false],
  ['getcare','Get care','Four doors: home, video, visits, results.',
   'June\'s re-cut: one at-home tile (the next screen picks the service), video visit, my visits, lab results. New house-with-cross glyph.', false],
  ['visits','Visits','Upcoming, In progress, Past.',
   'The old Appointments tab structure in the Lab-results tab component; pending requests and confirmed visits share Upcoming, with the status pill telling them apart. No work-order IDs.', false],
  ['notifs','Notifications','Now a tab: one feed for everything.',
   'Per the old design\'s nav: messages, lab results, crew updates, reminders and receipts in one place, each opening its real destination. New bell, heart-pulse and test-tube icons generated in both weights.', false],
  ['you','You','Status instead of a completion nag.',
   '"Profile management" from the feedback list: insurance, records, family, payment, sign out. The identity block opens Personal info.', false],
  ['profile','Personal info','Photo plus the basics, one field per edit.',
   'Net new. The Add photo button is a real picker in the live prototype (the image stays on-page); the nurse sees it at your door. Fields edit one at a time, never a funnel.', true],
  ['editfield','Edit a field','One field, one screen, save and back.',
   'Net new, was a stub. Every Details row opens this: the value, a note on where it is used, nothing else. The name feeds the greeting, the initials and the You block; the phone feeds the sign-in code screen.', true],
  ['insurance','Insurance card','Two photos. We do the typing.',
   'Net new, was a stub. Both capture tiles are working pickers. Saving clears the home-screen banner, fills the You row and switches the booking payment lines to the plan.', true],
  ['family','Family','The people you can book for.',
   'Net new, was a stub. Add a member with three fields and a relationship; they immediately become a bookable person under "Who is this for?" on Book a video visit.', true],
  ['payment','Payment methods','Cards on file, charged only after care.',
   'Net new, was a stub. Add a card, pick the default; the price screen and both booking screens follow the selection. The brand is read from the number, never asked.', true],
  ]],
  ['Video visit', [
  ['doctors','Choose a doctor','The searching step, restored and simplified.',
   'The old Search Provider form had 7 fields and demanded "at least two". Now: care team first, then ONE box that takes name, specialty, clinic, or a referral\'s NPI number. The specialty chips genuinely filter the list now (was a stub).', true],
  ['book','Book a video visit','Availability is the interface.',
   'The care-team path: you\'ve seen this doctor before, so times are the whole screen. Now with the payment row and optional doctor note (June, July 16), and family members are selectable under "Who is this for?".', false],
  ['confirmed','Booked','A booking is a booking.',
   'Care-team video visits confirm instantly; only new-doctor requests wait for the practice.', false],
  ['docprofile','Doctor profile','Who they are, then their times.',
   'Net new. The old flow jumped from a 44-result list straight to a request form.', true],
  ['vrequested','Video request sent','Honest pending for new-patient requests.',
   'Care-team bookings stay instant; a practice accepting a new patient genuinely takes time. Replaces the approval hourglass.', true],
  ['precall','Pre-call check','Stops a visit failing on a muted mic.',
   'Kept from round 1; the coworker\'s list keeps the secure video visit and waiting room.', false],
  ['waiting','Waiting room','A wait with an ETA is not a broken app.',
   'Kept. The old file named the room in provider settings but never designed it.', false],
  ['call','Video visit','Still here, just not the headline.',
   'Kept as-is: the old file had no in-call UI anywhere in 25,000 nodes.', false],
  ['postcall','After the visit','Ends by handing over to the crew.',
   'The post-call next step is the at-home draw: the two halves of the product meet here.', false],
  ]],
  ['At-home visit', [
  ['collect','Book the draw','Direct from home, or from a doctor\'s order.',
   'Patients can now start this themselves; a provider\'s order arrives prefilled in "What you need". The tests row and the address row both open real screens now and read live state.', false],
  ['tests','Change the tests','The order is editable, with live prices.',
   'Net new, was a stub. Check and uncheck tests; the booking row and the price ledger recompute. Dropping Dr. Anand\'s ordered panel gets a gentle warning, not a block.', true],
  ['address','Where we come','Saved addresses, or add one.',
   'Net new, was a stub. Home mirrors Personal info automatically; a new address takes three fields and becomes the draw destination.', true],
  ['price','The price','Locked before anything is charged.',
   'Unchanged on purpose: flat capped travel, card charged after the draw. The CTA now says <b>Request</b>, which is the truth.', false],
  ['requested','Requested','The honest version of "wait for approval".',
   'Net new. The old app ended every booking on a cartoon hourglass. Dispatch takes time, so we say so, show the next three steps, and promise a notification.', true],
  ['track','Tracking','The good status machine, given a screen worth it.',
   'The crew moment the feedback asked us to highlight: named nurse, live ETA, door code.', false],
  ['cancel','Cancel the visit','Honest about the one cost that stands.',
   'Net new, was a stub. Jennifer is en route, so the capped $12.50 travel line applies and the tests do not. Confirming cascades everywhere: home card gone, In progress empty, a Past entry, a notification.', true],
  ]],
  ['Records & messages', [
  ['results','Lab results','Value, range, verdict.',
   'Kept per June\'s call: the payoff of the crew visit is the result arriving in-app. All three tabs are real routes now, so back buttons and deep links behave.', false],
  ['resultsall','Results: All','Every draw, grouped by date.',
   'Net new, was a stub tab. Three draws back to January in the same value-range-verdict grammar, each dated and sourced.', true],
  ['trends','Results: Trends','Three numbers over six months.',
   'Net new, was a stub tab. Sparklines in the D2 grammar: ink line, electric endpoint when a value is behaving, coral when it is moving the wrong way. Each card says what to do about it.', true],
  ['summary','Visit summary','What was said, prescribed, ordered, next.',
   'Kept: history items open to something real instead of a dead end.', false],
  ['msgs','Messages','Named by people, never by ticket.',
   'No longer a tab: message notifications land in the Notifications feed, and the full list lives under You.', false],
  ['thread','Message thread','A conversation, with results pinned inside.',
   'Kept per June\'s call.', false],
  ['receipt','Receipt','A receipt that looks like a receipt.',
   'Net new, was a stub. The full ledger, the card, the timestamp and a reference code for the insurer or HSA, opened from the notification feed. Save as PDF is the one simulated control.', true],
  ]],
];
const SCREENS = SECTIONS.flatMap(([sec, list]) => list);
const FLOWS = [
  ['Sign in & sign up', [['welcome'], ['signup'], ['verify'], ['home']],
   'Returning patients skip Create account and go straight to the text code.'],
  ['Video visit', [['getcare'], ['doctors'], ['book', 'docprofile'], ['confirmed', 'vrequested'], ['precall'], ['waiting'], ['call'], ['postcall']],
   'Top path: your care team, instant. Bottom path: a new doctor, the practice confirms. Both continue at Pre-call check on visit day.'],
  ['At-home crew visit', [['home'], ['collect'], ['price'], ['requested'], ['track'], ['cancel']],
   'Tracking goes live once a nurse accepts; results land in Lab results afterwards. Cancelling from Tracking is a step of its own, honest about the one cost that stands.'],
  ['Booking side-doors', [['collect'], ['tests', 'address']],
   'Both open from rows on Booking and return there; the price ledger recomputes from whatever changes.'],
  ['Records & messages', [['visits'], ['summary'], ['results'], ['resultsall', 'trends'], ['thread']],
   'Messages also open from You and from message notifications. All three results tabs are real routes.'],
  ['You & account', [['you'], ['profile', 'insurance', 'family', 'payment'], ['editfield']],
   'Every row on You opens a real screen now. The last step belongs to Personal info: each Details row edits one field at a time.'],
  ['Notifications fan-out', [['notifs'], ['track', 'thread', 'precall', 'results', 'receipt']],
   'Every notification opens its real destination, including the payment receipt.'],
];
/* All ten 'stub' items were built on 2026-07-16 and moved up into
   SECTIONS as real screens; only planned/parked work remains. */
const BACKLOG = [
  ['Sign in & sign up', [
    ['Wrong-code error', 'planned'],
    ['Under-18 path', 'planned'],
    ['Terms & privacy', 'planned'],
  ]],
  ['Video visit', [
    ['Reschedule / cancel visit', 'planned'],
    ['Request declined by practice', 'planned'],
  ]],
  ['At-home visit', [
    ['"Nurse accepted" moment', 'planned'],
    ['Unable to draw / nurse delayed', 'planned'],
  ]],
  ['Records & messages', [
    ['Visits search', 'parked'],
  ]],
  ['System states', [
    ['Loading / error / offline', 'planned'],
    ['Empty states (visits, notifs)', 'planned'],
  ]],
];
