/* Shared screen + flow data for the R2 galleries and flow map.
   Source of truth: edit here; index-r2.html, flowmap-r2.html and
   the artifact builder all consume this file.
   Entry shape: [hash, title, sub, annotation, isNew, hiddenInV1].
   hiddenInV1 (June, 2026-07-17): the screen stays in its home
   category but renders grayed under a "View design" veil, because
   V1 hides it (pricing moved to V2; see V2-FEATURES.md). */
const SECTIONS = [
  ['Sign in & sign up', [
  ['splash','Launch','The brand moment while the app wakes.',
   'Net new, was the "App launch loading" chip. The F20 mark (the cross with speed streaks, June\'s pick from 25 logo concepts + 22 developments) teleports in on electric; a tap moves on.', true],
  ['onboard','Onboarding','Three full-bleed slides before sign-in.',
   'Net new, was the "Onboarding intro screens" chip. June\'s direction E: the photo fills the screen, an ink scrim keeps the light editorial type readable, volt carries the key phrase. Skip is always one tap; nothing is collected here.', true],
  ['welcome','Sign in','One step: phone number, code by text.',
   'Subline now leads with the at-home service. "Create an account" is finally visible.', false],
  ['signup','Create account','Four fields. That is the whole form.',
   'Net new. The old sign-up funneled documents, dependents and insurance before any care; identity is enough to start.', true],
  ['verify','Text code','One code serves sign-in and sign-up.',
   'Net new. Each digit box is its own 46&times;56 target, above the 44px floor.', true],
  ]],
  ['Main navigation', [
  ['home','Home','The hero is now the thing only Teleport does.',
   '<b>Crew first:</b> "A licensed nurse, at your door" leads; the video visit is one quiet row below it.', false],
  ['getcare','Get care','Four doors: home, video, visits, results.',
   'June\'s re-cut: one at-home tile (the next screen picks the service), video visit, my visits, lab results. New house-with-cross glyph.', false],
  ['visits','Visits','Upcoming, In progress, Past.',
   'The old Appointments tab structure in the Lab-results tab component; pending requests and confirmed visits share Upcoming, with the status pill telling them apart. No work-order IDs.', false],
  ['notifs','Notifications','Now a tab: one feed for everything.',
   'Per the old design\'s nav: messages, lab results, crew updates and reminders in one place, each opening its real destination. (The receipt item is hidden with pricing until V2.) New bell, heart-pulse and test-tube icons generated in both weights.', false],
  ['you','You','Status instead of a completion nag.',
   '"Profile management" from the feedback list: insurance, records, family, payment, sign out. The identity block opens Personal info.', false],
  ['profile','Personal info','Photo plus the basics, one field per edit.',
   'Net new. The Add photo button is a real picker in the live prototype (the image stays on-page); the nurse sees it at your door. Fields edit one at a time, never a funnel.', true],
  ['editfield','Edit a field','One field, one screen, save and back.',
   'Net new, was a stub. Every Details row opens this: the value, a note on where it is used, nothing else. The name feeds the greeting, the initials and the You block; the phone feeds the sign-in code screen.', true],
  ['insurance','Insurance card','Two photos. We do the typing.',
   'Net new, was a stub. Both capture tiles are working pickers. Saving clears the home-screen banner, fills the You row and switches the booking payment lines to the plan.', true],
  ['family','Family','The people you can book for.',
   'Net new, was a stub. Add a member with three fields and a relationship; they immediately become a bookable person under "Who is this for?" on Book a video visit.', true],
  ['payment','Payment methods','Cards on file, charged only after care.',
   'Hidden in V1 (pricing moved to V2, team call 2026-07-17). Fully working: add a card, pick the default, brand read from the number. V1 shows a quiet "coming soon" row on You instead. Tracked in V2-FEATURES.md.', true, true],
  ]],
  ['Video visit', [
  ['doctors','Choose a doctor','The searching step, restored and simplified.',
   'The old Search Provider form had 7 fields and demanded "at least two". Now: care team first, then ONE box that takes name, specialty, clinic, or a referral\'s NPI number. The specialty chips genuinely filter the list now (was a stub).', true],
  ['book','Book a video visit','Availability is the interface.',
   'The care-team path: you\'ve seen this doctor before, so times are the whole screen. Family members are selectable under "Who is this for?"; the payment row reads Cash in V1 (pricing is V2) and the optional doctor note stays.', false],
  ['confirmed','Booked','A booking is a booking.',
   'Care-team video visits confirm instantly; only new-doctor requests wait for the practice.', false],
  ['docprofile','Doctor profile','Who they are, then their times.',
   'Net new. The old flow jumped from a 44-result list straight to a request form.', true],
  ['vrequested','Video request sent','Honest pending for new-patient requests.',
   'Care-team bookings stay instant; a practice accepting a new patient genuinely takes time. Replaces the approval hourglass.', true],
  ['precall','Pre-call check','Stops a visit failing on a muted mic.',
   'Kept from round 1; the coworker\'s list keeps the secure video visit and waiting room.', false],
  ['waiting','Waiting room','A wait with an ETA is not a broken app.',
   'Kept. The old file named the room in provider settings but never designed it.', false],
  ['call','Video visit','Still here, just not the headline.',
   'Kept as-is: the old file had no in-call UI anywhere in 25,000 nodes.', false],
  ['postcall','After the visit','Ends by handing over to the crew.',
   'The post-call next step is the at-home draw: the two halves of the product meet here.', false],
  ]],
  ['At-home visit', [
  ['collect','Book the draw','Direct from home, or from a doctor\'s order.',
   'Patients can now start this themselves; a provider\'s order arrives prefilled in "What you need". The tests row and the address row both open real screens and read live state. V1 requests directly (pricing is V2), so the CTA says "Request the visit".', false],
  ['tests','Change the tests','The order is editable.',
   'Net new, was a stub. Check and uncheck tests; the booking row recomputes. Dropping Dr. Anand\'s ordered panel gets a gentle warning, not a block. (Per-test prices return with pricing in V2.)', true],
  ['address','Where we come','Saved addresses, or add one.',
   'Net new, was a stub. Home mirrors Personal info automatically; a new address takes three fields and becomes the draw destination.', true],
  ['price','The price','The locked, itemized cost before requesting.',
   'Hidden in V1 (pricing moved to V2, team call 2026-07-17). Fully designed and working: flat capped travel, computed ledger, price-locked promise. V1 skips from Booking straight to Requested. Tracked in V2-FEATURES.md.', false, true],
  ['requested','Requested','The honest version of "wait for approval".',
   'Net new. The old app ended every booking on a cartoon hourglass. Dispatch takes time, so we say so, show the next three steps, and promise a notification.', true],
  ['track','Tracking','The good status machine, given a screen worth it.',
   'The crew moment the feedback asked us to highlight: named nurse, live ETA, door code.', false],
  ['cancel','Cancel the visit','Turning a nurse around, told straight.',
   'Net new, was a stub. Confirming cascades everywhere: home card gone, In progress empty, a Past entry, a notification, and the test order is kept for rebooking. (Charge honesty copy returns with pricing in V2.)', true],
  ]],
  ['Records & messages', [
  ['results','Lab results','Value, range, verdict.',
   'Kept per June\'s call: the payoff of the crew visit is the result arriving in-app. All three tabs are real routes now, so back buttons and deep links behave.', false],
  ['resultsall','Results: All','Every draw, grouped by date.',
   'Net new, was a stub tab. Three draws back to January in the same value-range-verdict grammar, each dated and sourced.', true],
  ['trends','Results: Trends','Three numbers over six months.',
   'Net new, was a stub tab. Sparklines in the D2 grammar: ink line, electric endpoint when a value is behaving, coral when it is moving the wrong way. Each card says what to do about it.', true],
  ['summary','Visit summary','What was said, prescribed, ordered, next.',
   'Kept: history items open to something real instead of a dead end.', false],
  ['msgs','Messages','Named by people, never by ticket.',
   'No longer a tab: message notifications land in the Notifications feed, and the full list lives under You.', false],
  ['thread','Message thread','A conversation, with results pinned inside.',
   'Kept per June\'s call.', false],
  ['receipt','Receipt','The paid ledger with card and reference.',
   'Hidden in V1 (pricing moved to V2, team call 2026-07-17): no charges in V1 means no receipts. The design stays ready, including the notification-feed entry that opens it. Tracked in V2-FEATURES.md.', true, true],
  ]],
];
const SCREENS = SECTIONS.flatMap(([sec, list]) => list);
const FLOWS = [
  ['Sign in & sign up', [['splash'], ['onboard'], ['welcome'], ['signup'], ['verify'], ['home']],
   'First launch: the splash and three intro slides (Skip works from any of them). Returning patients skip Create account and go straight to the text code.'],
  ['Video visit', [['getcare'], ['doctors'], ['book', 'docprofile'], ['confirmed', 'vrequested'], ['precall'], ['waiting'], ['call'], ['postcall']],
   'Top path: your care team, instant. Bottom path: a new doctor, the practice confirms. Both continue at Pre-call check on visit day.'],
  ['At-home crew visit', [['home'], ['collect'], ['requested'], ['track'], ['cancel']],
   'V1 requests directly from Booking (the price step is V2). Tracking goes live once a nurse accepts; results land in Lab results afterwards.'],
  ['Booking side-doors', [['collect'], ['tests', 'address']],
   'Both open from rows on Booking and return there; the order updates from whatever changes.'],
  ['Records & messages', [['visits'], ['summary'], ['results'], ['resultsall', 'trends'], ['thread']],
   'Messages also open from You and from message notifications. All three results tabs are real routes.'],
  ['You & account', [['you'], ['profile', 'insurance', 'family'], ['editfield']],
   'Every row on You opens a real screen now (Payment is a quiet placeholder until V2). The last step belongs to Personal info: each Details row edits one field at a time.'],
  ['Notifications fan-out', [['notifs'], ['track', 'thread', 'precall', 'results']],
   'Every notification opens its real destination. (The receipt notification returns with pricing in V2.)'],
];
/* All ten 'stub' items were built on 2026-07-16 and moved up into
   SECTIONS as real screens; only planned/parked work remains. */
const BACKLOG = [
  ['Sign in & sign up', [
    ['Wrong-code error', 'planned'],
    ['Under-18 path', 'planned'],
    ['Terms & privacy', 'planned'],
  ]],
  ['Video visit', [
    ['Reschedule / cancel visit', 'planned'],
    ['Request declined by practice', 'planned'],
  ]],
  ['At-home visit', [
    ['"Nurse accepted" moment', 'planned'],
    ['Unable to draw / nurse delayed', 'planned'],
  ]],
  ['Records & messages', [
    ['Visits search', 'parked'],
  ]],
  ['System states', [
    ['Loading / error / offline', 'planned'],
    ['Empty states (visits, notifs)', 'planned'],
  ]],
];
